--
CREATE SEQUENCE SEQ_ANIMAL
START WITH 1
INCREMENT BY 10;

CREATE TABLE TBL_ANIMAL(
	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
	ANIMAL_NAME VARCHAR2(225) NOT NULL UNIQUE,
	ANIMAL_AGE NUMBER DEFAULT 0,
	ANIMAL_COLOR VARCHAR2(225)
);

INSERT INTO TBL_ANIMAL
VALUES(SEQ_ANIMAL.NEXTVAL, '진', 5, '갈색');

SELECT *FROM TBL_ANIMAL;
-- 컬럼 이름 변경
-- RENAME A TO B: 테이블의 이름을 변경
-- RENAME COLUMN TO B: 테이블의 컬럼 이름 변경
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_LOVE;
ALTER TABLE TBL_ANIMAL RENAME TO TBL_PET;

-- PK키는 이름을 바로 바꿀 수 없다.
-- PK키를 삭제하고, 다시 추가해야한다.
-- 단, FK키가 참조하고 있는 경우 삭제할 수 없다.
-- DROP CONSTRAINT: 제약조건 삭제


-- 외래키
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(225),
	USER_AGE NUMBER
);

CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(225)
);

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(225),
	POST_CONTENT VARCHAR(225),
	USER_ID NUMBER,
	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);

-- 요구사항
-- 회사에서 광고를 여러개 신청하려고 합니다.
-- 회사, 광고, 신청 테이블을 만들어주세요.
CREATE SEQUENCE SEQ_COMPANY1;
CREATE TABLE TABLE_COMPANY1(
	ID NUMBER CONSTRAINT PK_COMPANY1 PRIMARY KEY,
	COMPANY1_NAME VARCHAR2(225)
);
 
CREATE SEQUENCE SEQ_ADVER1;
CREATE TABLE TABLE_ADVER1(
	ID NUMBER CONSTRAINT PK_AVDER1 PRIMARY KEY,
	ADVER1_NAME VARCHAR2(225)
);

CREATE SEQUENCE SEQ_FORM1;
CREATE TABLE TABLE_FORM1(
	ID NUMBER CONSTRAINT PK_FORM1 PRIMARY KEY,
	COMPANY1_ID NUMBER,
	ADVER1_ID NUMBER,
	CONSTRAINT FK_FORM1_COMPANY1 FOREIGN KEY(COMPANY1_ID)
	REFERENCES TABLE_COMPANY1(ID),
	CONSTRAINT FK_FORM1_ADVER1 FOREIGN KEY(ADVER1_ID)
	REFERENCES TABLE_ADVER1(ID)
);


-- 요구 사항
-- 회원이 존재하고 회원은 여러 상품을 구매할 수 있습니다.
-- 데이터 베이스 시스템을 만들어주세요.
-- MEMBER
-- 이름, 나이, 핸드폰, 주소, 등급, ...
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(225),
	MEMBER_AGE NUMBER
);

CREATE SEQUENCE SEQ_PRODUCT2;
CREATE TABLE TBL_PRODUCT2(
	ID NUMBER CONSTRAINT PK_PRODUCT2 PRIMARY KEY,
	PRODUCT2_NAME VARCHAR2(225),
	PRODUCT2_AGE VARCHAR2(225)
	);

CREATE SEQUENCE SEQ_LIST;
CREATE TABLE TBL_LIST(
	ID NUMBER CONSTRAINT PK_LIST PRIMARY KEY,
	MEMBER_ID NUMBER,
	PRODUCT2_ID NUMBER,
	CONSTRAINT FK_LIST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_LIST_PRODUCT2 FOREIGN KEY(PRODUCT2_ID)
	REFERENCES TBL_PRODUCT2(ID)
);

-- 요구사항
-- 상품 판매자(TBL_SELLER)가 상품 구매자(TBL_BUYER)에게
-- 배송(TBL_DELEVERY)을 할 수 있는 기능이 필요해요.
-- 판매자: 음료, 음료 종류, 음료 크기, 만든 날짜


CREATE SEQUENCE SEQ_SELLER;
CREATE TABLE TBL_SELLER(
	ID NUMBER CONSTRAINT PK_SELLER PRIMARY KEY,
	SELLER_DRINTK VARCHAR2(225),
	SELLER_DRINK_VOLUME NUMBER,
	SELLER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	);

CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
	ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
	BUYER_NAME VARCHAR2(225) NOT NULL,
	BUYER_PHONE VARCHAR2(225),
	BUYER_ADDRESS VARCHAR2(225)
);

CREATE SEQUENCE SEQ_DELEVERY;
CREATE TABLE TBL_DELEVERY(
	ID NUMBER CONSTRAINT PK_DELEVERY PRIMARY KEY,
	DELEVERY_STATUS CHAR(10),
	DELEVERY_START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	SELLER_ID NUMBER,
	BUYER_ID NUMBER,
	CONSTRAINT FK_DELEVERY_SELLER FOREIGN KEY(SELLER_ID)
	REFERENCES TBL_SELLER(ID),
	CONSTRAINT FK_DELIVERY_BUYER FOREIGN KEY(BUYER_ID)
	REFERENCES TBL_BUYER(ID)
);

/*
	요구사항
	유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
	아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
	체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
	아이들은 여러 번 체험학습에 등록할 수 있어요.
*/


CREATE SEQUENCE SEQ_CHILD;
CREATE TABLE TBL_CHILD(
	ID NUMBER CONSTRAINT PK_CHILD PRIMARY KEY,
	CHILD_NAME VARCHAR2(225) NOT NULL,
	CHILD AGE NUMBER
);

CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_
);




