

--회원이 존재하고 회원은 여러 상품을 구매할 수 있습니다, MEMBER , MART , FORM
-- 데이터 베이스 시스템 을 만들어주세요


CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR(225) NOT NULL,
	MEMBER_PHONE VARCHAR(225)
);

CREATE SEQUENCE SEQ_MART;
CREATE TABLE TBL_MART(
	ID NUMBER CONSTRAINT PK_MART PRIMARY KEY,
	MART_PRODUCT VARCHAR2(225) NOT NULL,
	MART_PRICE NUMBER
);


CREATE SEQUENCE SEQ_FORM;
CREATE TABLE TBL_FORM(
	ID NUMBER CONSTRAINT PK_FORM PRIMARY KEY,
	MEMBER_ID NUMBER,
	MART_ID NUMBER,
	CONSTRAINT FK_FORM_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_FORM_MART FOREIGN KEY(MART_ID)
	REFERENCES TBL_MART(ID)
);

--상품 판매자 가 구매가에게 
-- 배송을 할 수 있는 기능 
-- 판매자 = 음료 이름 종류 크기 만든 날짜
-- 구매자 이름, 전화번호, 주소

CREATE SEQUENCE SEQ_SELLER;
CREATE TABLE TBL_SELLER(
	ID NUMBER CONSTRAINT PK_SELLER PRIMARY KEY,
	SELLER_PRODUCT_NAME VARCHAR2(225),
	SELLER_PRODUCT_TYPE VARCHAR2(225),
	SELLER_PRODUCT_SIZE NUMBER,
	SELLER_PROCDUCT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
	ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
	BUYER_NAME VARCHAR2(225),
	BUYER_PHONE VARCHAR2(225),
	BUYER_ADDRESS VARCHAR2(225)
);


CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY(
	ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
	DELIVERY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DELIVERY_STATUS CHAR(10),
	SELLER_ID NUMBER,
	BUYER_ID NUMBER,
	CONSTRAINT FK_DELIVERY_SELLER FOREIGN KEY(SELLER_ID)
	REFERENCES TBL_SELLER(ID),
	CONSTRAINT FK_DELIVERY_BUYER FOREIGN KEY(BUYER_ID)
	REFERENCES TBL_BUYER(ID)
);




