-- 게시판 최신글 정렬
SELECT TP.ID, TP.POST_TITLE, TU.USER_EMAIL
FROM TBL_POST TP -- 앞에 있는 테이블이 FK가짐
JOIN TBL_USER TU
ON TP.USER_ID = TU.ID
ORDER BY ID DESC; 

-- 댓글을 단 사용자
/*SELECT TR.REPLY_CONTENT, TU.USER_EMAIL
FROM TBL_REPLY TR
JOIN TBL_USER TU
ON TR.USER_ID = TU.ID;
WHERE
GROUP BY
HAVING 
ORDER BY */
/* SQL의 실행 순서
FROM - JOIN - ON - WHERE - GROUP BY - HAVING - SELECT - ORDER BY
*/
-- 주문자 정보 조회
--주문 날짜와 사용자의 이름

SELECT TBO.ORDER_START_DATE, TBB.BUYER.NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID;

-- 가장 인기 많은 상품을 구매한 사용자의 정보와 상품 이름 조회
-- 가장 인기 많은 상품을 = 가장 주문이 많은 ORDER
SELECT PRODUCT_ID, COUNT(PRODUCT_ID)
FROM TBL_ORDER
GROUP BY PRODUCT_ID
ORDER BY COUNT(PRODUCT_ID) DESC;
-- PRODUCT 3 = ORDER 7
-- 상품에서 구매자랑 주문 많이 한 사람 
-- 상품의 아이디와 주문의 아이디 주문에서 유
-- 주문 한 곳에서 유저의 아이디 추가하면 됨
-- 
SELECT *
FROM TBL_USER
WHERE ID = (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID)
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	ORDER BY COUNT(PRODUCT_ID) DESC
	
);


-- TEACHER
-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT TBU.*, TBP.PRODUCT_NAME
FROM (
   SELECT *
   FROM TBL_ORDER TBO
   WHERE PRODUCT_ID = (
      SELECT PRODUCT_ID
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
      HAVING COUNT(PRODUCT_ID) = (
         SELECT MAX(COUNT(PRODUCT_ID))
         FROM TBL_ORDER
         GROUP BY PRODUCT_ID
      )
   )
) TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;



-- 가장 인기 많은 상품을 구매한 
-- 사용자의 정보와 상품 이름을 조회
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
WHERE TBP.ID = (
   SELECT PRODUCT_ID
   FROM TBL_ORDER
   GROUP BY PRODUCT_ID
   HAVING COUNT(PRODUCT_ID) = (
      SELECT MAX(COUNT(PRODUCT_ID))
      FROM TBL_ORDER
      GROUP BY PRODUCT_ID
   )
);

-- 1) 상품 이름과 총 판매 매출 조회
SELECT TBP.PRODUCT_NAME, TBP.PRODUCT_PRICE , TBU.BUYER_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;
---신발을 몇명이 샀는지
SELECT TBP.PRODUCT_NAME, TBP.PRODUCT_PRICE , TBU.BUYER_NAME
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

-- TEACHER
SELECT PRODUCT_NAME, COUNT(PRODUCT_ID) * PRODUCT_PRICE
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY PRODUCT_ID, PRODUCT_PRICE, PRODUCT_NAME;



-- 2) 상품을 구매한 20 ~ 30대 구매자의 수 조회

SELECT * 
FROM TBL_BUYER
WHERE BUYER_AGE <= 30 AND BUYER_AGE >= 20;

SELECT COUNT(TBO.BUYER_ID), TBO.PRODUCT_ID
FROM TBL_ORDER TBO
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID 
WHERE TBB.ID IN (
	SELECT ID
	FROM TBL_BUYER
	WHERE BUYER_AGE < 30 AND BUYER_AGE >=20
)
GROUP BY TBO.BUYER_ID, TBO.PRODUCT_ID ;

--=================

 -- 1.
	SELECT ID
	FROM TBL_BUYER
	WHERE BUYER_AGE < 30 AND BUYER_AGE >=20
	
 -- 2. 
	--테이블 오더에서 개수
	SELECT COUNT(ID) || '권' AS "20-30대"
	FROM TBL_ORDER
	WHERE BUYER_ID IN (
		SELECT ID
		FROM TBL_BUYER
		WHERE BUYER_AGE < 30 AND BUYER_AGE >=20
	);

-- 3) 뉴발란스를 구매한 20대 구매자의 이름 조회
SELECT *
FROM TBL_PRODUCT
WHERE PRODUCT_BRAND  = '뉴발란스';





/*4) 여성의 나이대별 평균 지출 금액 조회
5) 쇼핑몰의 총 판매 액수 조회
6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
7) 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회
8) 30대 남성이 가장 많이 구매한 상품의 이름 조회
9) 가장 적게 판매된 상품의 이름
10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
12) 가장 인기가 없는 상품 조회*/


--4 여성의 나이대별 평균 지출 금액 조회
	--4.1 여성의 나이대별
--나이
SELECT ID, BUYER_NAME , BUYER_GENDER, BUYER_AGE
FROM TBL_BUYER
WHERE BUYER_GENDER = '여'
GROUP BY BUYER_GENDER, BUYER_AGE, BUYER_NAME, ID ;

-- 나이대 별
SELECT BUYER_AGE, COUNT(BUYER_AGE) 
FROM TBL_BUYER
WHERE BUYER_GENDER = '여'
GROUP BY BUYER_AGE;

-- 평균 금액
SELECT TBB.BUYER_AGE, COUNT(TBB.BUYER_AGE), AVG(TBP.PRODUCT_PRICE)
FROM (
	SELECT ID , BUYER_AGE, BUYER_NAME
	FROM TBL_BUYER
	WHERE BUYER_GENDER = '여'
	GROUP BY BUYER_AGE, ID , BUYER_NAME
) TBB
JOIN TBL_ORDER TBO 
ON TBO.BUYER_ID = TBB.ID
JOIN TBL_PRODUCT TBP 
ON TBP.ID = TBO.PRODUCT_ID
GROUP BY TBB.BUYER_AGE;


--5) 쇼핑몰의 총 판매 액수 조회
--제품과 주문
SELECT SUM(COUNT(PRODUCT_ID) * TBP.PRODUCT_PRICE ) 
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
GROUP BY TBO.PRODUCT_ID, TBP.PRODUCT_PRICE ;




--6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회

--TEACHER
-- 6) 가장 매출이 적은 상품을 구매한 사용자의 이름과, 상품명 조회
SELECT TBU.BUYER_NAME, TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBU
ON TBO.BUYER_ID = TBU.ID
WHERE PRODUCT_ID = (
   SELECT ID
   FROM (
      SELECT TBP.ID
      FROM TBL_ORDER TBO
      JOIN TBL_PRODUCT TBP
      ON TBO.PRODUCT_ID = TBP.ID
      JOIN TBL_BUYER TBU
      ON TBO.BUYER_ID = TBU.ID
      GROUP BY TBP.ID, TBP.PRODUCT_BRAND, TBP.PRODUCT_PRICE
      ORDER BY SUM(TBP.PRODUCT_PRICE)
   )
   WHERE ROWNUM = 1
);


--====================================================================
SELECT COUNT(PRODUCT_ID)*TBP.PRODUCT_PRICE,TBP.PRODUCT_NAME 
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
GROUP BY PRODUCT_ID, TBP.PRODUCT_PRICE, TBP.PRODUCT_NAME 
ORDER BY PRODUCT_ID;


SELECT MIN(COUNT(PRODUCT_ID)*TBP.PRODUCT_PRICE)
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
GROUP BY PRODUCT_ID, TBP.PRODUCT_PRICE 
ORDER BY PRODUCT_ID;


--7 경기도에 거주한 사람이 구매한 상품과, 사용자 정보를 조회

SELECT TBP.*, TBB.*
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
WHERE TBB.BUYER_ADDRESS LIKE '%경기도%';


--8 30대 남성이 가장 많이 구매한 상품의 이름 조회

SELECT COUNT(TBP.PRODUCT_NAME), TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
WHERE TBB.BUYER_GENDER = '남'
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBP.PRODUCT_NAME);


SELECT *
FROM(
	SELECT COUNT(TBP.PRODUCT_NAME), TBP.PRODUCT_NAME
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	JOIN TBL_BUYER TBB
	ON TBO.BUYER_ID = TBB.ID 
	WHERE TBB.BUYER_GENDER = '남' AND TBB.BUYER_AGE BETWEEN 30 AND 39
	GROUP BY TBP.PRODUCT_NAME
	ORDER BY COUNT(TBP.PRODUCT_NAME) DESC
)
WHERE ROWNUM = 1 ;

--TEACHER===========

SELECT COUNT(TBP.PRODUCT_NAME), TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
WHERE TBB.BUYER_GENDER = '남' AND TBB.BUYER_AGE BETWEEN 30 AND 39
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBP.PRODUCT_NAME);

--================================================

SELECT COUNT(TBP.PRODUCT_NAME), TBP.PRODUCT_NAME
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID 
WHERE TBB.BUYER_GENDER = '남' AND TBB.BUYER_AGE BETWEEN 30 AND 39
GROUP BY TBP.PRODUCT_NAME
ORDER BY COUNT(TBP.PRODUCT_NAME);







--9) 가장 적게 판매된 상품의 이름
-- 기본
SELECT *
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID;
--
SELECT TBP.PRODUCT_NAME , COUNT(PRODUCT_ID)
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
GROUP BY PRODUCT_ID, TBP.PRODUCT_NAME 
ORDER BY COUNT(PRODUCT_ID);
--
SELECT PRODUCT_NAME
FROM(
	SELECT TBP.PRODUCT_NAME , COUNT(PRODUCT_ID)
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	JOIN TBL_BUYER TBB
	ON TBO.BUYER_ID = TBB.ID
	GROUP BY PRODUCT_ID, TBP.PRODUCT_NAME 
	ORDER BY COUNT(PRODUCT_ID)
)
WHERE ROWNUM < 3;


--10) 평균 나이보다 많은 사용자들이 구매한 상품과 사용자의 정보 조회
-- 평균 나이보다 많은 사용자

SELECT AVG(BUYER_AGE) 
FROM TBL_BUYER;


SELECT TBP.PRODUCT_NAME, TBB.*
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE TBB.BUYER_AGE > (
	SELECT AVG(BUYER_AGE) 
	FROM TBL_BUYER
);


--11) 20대 여성이 구매한 상품 이름과 주문 건수 조회
SELECT *
FROM TBL_BUYER
WHERE BUYER_GENDER = '여'AND BUYER_AGE BETWEEN 20 AND 29;



--20대 여성
SELECT BUYER_NAME
FROM(
SELECT *
FROM TBL_BUYER
WHERE BUYER_AGE BETWEEN 20 AND 29;
)
WHERE BUYER_GENDER = '여';
--==


SELECT TBP.PRODUCT_NAME , COUNT(TBP.PRODUCT_NAME)
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE TBB.ID IN (
SELECT ID 
FROM(
SELECT *
FROM TBL_BUYER
WHERE BUYER_AGE >= 20 AND BUYER_AGE < 30
)
WHERE BUYER_GENDER = '여')
GROUP BY TBP.PRODUCT_NAME;




--12) 가장 인기가 없는 상품 조회*/
SELECT PRODUCT_ID 
FROM (
	SELECT PRODUCT_ID, COUNT(PRODUCT_ID)
	FROM TBL_ORDER
	GROUP BY PRODUCT_ID
	ORDER BY COUNT(PRODUCT_ID)
)
WHERE ROWNUM <3;


SELECT TBP.*
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_BUYER TBB
ON TBO.BUYER_ID = TBB.ID
WHERE TBP.ID IN (
	SELECT PRODUCT_ID 
	FROM (
		SELECT PRODUCT_ID, COUNT(PRODUCT_ID)
		FROM TBL_ORDER
		GROUP BY PRODUCT_ID
		ORDER BY COUNT(PRODUCT_ID)
	)
	WHERE ROWNUM <3
);


-- TEACHER

-- 처음부터  ~개 : FETCH FIRST 2 ROWS ONLY
-- OFFSET 행 다음부터 몇 개 : OFFSET 3 ROWS FETCH NECT 2 ROWS ONLY;




