CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER,
   PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
   ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
   MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
   MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
   MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
   MEMBER_ID NUMBER NOT NULL,
   PRODUCT_ID NUMBER NOT NULL,
   PRODUCT_COUNT NUMBER DEFAULT 1,
   CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID),
   CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
   REFERENCES TBL_PRODUCT(ID)
);


SELECT * FROM TBL_ORDER to2 ;

INSERT INTO TBL_PRODUCT 
VALUES(SEQ_MEMBER.NEXTVAL, '텀블러', 1000, 1);
INSERT INTO TBL_PRODUCT 
VALUES(SEQ_MEMBER.NEXTVAL, '공책', 100, 13);
INSERT INTO TBL_PRODUCT 
VALUES(SEQ_MEMBER.NEXTVAL, #{memberId}, #{productId}, #{productCount})

INSERT INTO TBL_ORDER 
VALUES(SEQ_MEMBER.NEXTVAL, 1, 1, 1);

SELECT ID
FROM TBL_MEMBER
WHERE MEMBER_EMAIL = #{memberEmail}



SELECT * FROM TBL_PRODUCT tp ;
SELECT * FROM TBL_MEMBER tm ;
SELECT * FROM TBL_ORDER to2 ;


UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = #{productName}, PRODUCT_PRICE = #{productPrice}, PRODUCT_STOCK = #{productStock},
WHERE ID = #{id}

SELECT *
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID 
JOIN TBL_MEMBER TBM 
ON TBO.MEMBER_ID = TBM.ID 

-- 오더 아이디가 있으면 상품 아이디와 구매자 아이디 있음, 
SELECT 
	TBO.ID,
	TBO.MEMBER_ID, 
	TBO.PRODUCT_ID,
	TBO.PRODUCT_COUNT,
	TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE AS "ORDER_TOTAL_PRICE",
	TBP.PRODUCT_NAME, 
	TBP.PRODUCT_PRICE, 
	TBP.PRODUCT_STOCK,
	TBM.MEMBER_EMAIL, 
	TBM.MEMBER_NAME 
FROM TBL_ORDER TBO
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID
JOIN TBL_MEMBER TBM 
ON TBO.MEMBER_ID = TBM.ID 
ORDER BY TBO.ID DESC;

	SELECT 
		TBO.ID,
		TBO.MEMBER_ID, 
		TBO.PRODUCT_ID,
		TBO.PRODUCT_COUNT,
		TBO.PRODUCT_COUNT * TBP.PRODUCT_PRICE AS "ORDER_TOTAL_PRICE",
		TBP.PRODUCT_NAME, 
		TBP.PRODUCT_PRICE, 
		TBP.PRODUCT_STOCK,
		TBM.MEMBER_EMAIL, 
		TBM.MEMBER_NAME 
	FROM TBL_ORDER TBO
	JOIN TBL_PRODUCT TBP
	ON TBO.PRODUCT_ID = TBP.ID
	JOIN TBL_MEMBER TBM 
	ON TBO.MEMBER_ID = TBM.ID 
	WHERE TBM.ID = 1
	ORDER BY TBO.ID DESC;






