CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(225) NOT NULL,
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER DEFAULT 0
);
-- 테이블을 만들고 VO 를 만들기 ( RDB 중심 설계 )


SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 3;

-- 다 안 바꾸더라고 다 바꾸고 
UPDATE TBL_PRODUCT
SET 
	PRODUCT_NAME =#{productName}, 
	PRODUCT_PRICE = #{productPrice}, 
	PRODUCT_STOCK = #{productStock}
WHERE ID = #{id}

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(225) NOT NULL,
	POST_CONTENT VARCHAR2(225) NOT NULL
);


INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, 'JS', 'MAR');

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, 'F', 'APPA');

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '롯데', '가을 야구 가능성');

INSERT INTO TBL_POST
VALUES(SEQ_POST.NEXTVAL, '날씨', '비');

SELECT ID, POST_TITLE,POST_CONTENT
FROM TBL_POST
WHERE ID = #{id}



UPDATE TBL_POST
SET POST_TITLE = #{postTitle}, 
SET POST_CONTENT = #{postContent}, 
WHERE ID = #{id}

SELECT * FROM TBL_POST;


