CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR2(255)
);


-- 상품 PRODUCT
-- 상품 이름, 상품 가격, 상품 재고, 상품 설명
CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY, 
	PRODUCT_NAME VARCHAR2(225) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,
	PRODUCT_INTRODUCE VARCHAR2(225)
);

--SQL의 값은 '' 싱글 쿼터
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '맥북', 1500000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE)
VALUES(SEQ_PRODUCT.NEXTVAL, '그램', 15000);

DROP TABLE TBL_PRODUCT;

SELECT * FROM TBL_PRODUCT;


-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER;


-- 컬럼 수정, 새로운 데이터부터 적용
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;


-- MEMBER TABLE
-- 이름 나이 성별 주소
-- ID => 시퀀스
-- 사용자 2명 추가
-- 등급 컬럼 CHAR추가,
-- 등급 컬럼을  VARCHAR2

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(225) NOT NULL,
	MEMBER_AGE NUMBER NOT NULL,
	MEMBER_GENDER VARCHAR2(225),
	MEMBER_ADDRESS VARCHAR2(225)
);


INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_PRODUCT.NEXTVAL, 'LEE', 10, 'FE', 'BONALEE');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_PRODUCT.NEXTVAL, 'KO', 10, 'FE', 'KOFF');


DROP TABLE TBL_MEMBER;


SELECT * FROM TBL_MEMBER;

-- 등급 컬럼 CHAR추가,
-- 등급 컬럼을  VARCHAR2
ALTER TABLE TBL_MEMBER ADD MEMBER_CLASS CHAR(225);
ALTER TABLE TBL_MEMBER  MODIFY MEMBER_CLASS VARCHAR2(225);
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_CLASS;




