/*안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
	광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소, 중견, 대기업)입니다.
	광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
	기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다. */

-- 기업, 광고, 대, 중, 소, 신청
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(225) NOT NULL,
	COMPANY_ADDRESS VARCHAR2(225),
	COMPANY_KIND VARCHAR2(224) NOT NULL,
	CONSTRAINT BAN_KIND CHECK(COMPANY_KIND IN ('스타트업','중소', '중견', '대기업'))
	);
	
CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD(
	ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
	AD_TITLE VARCHAR2(225)
	);

CREATE SEQUENCE SEQ_BIGCATEGORY;
CREATE TABLE TBL_BIGCATEGORY(
	ID NUMBER CONSTRAINT PK_BIGCATEGORY PRIMARY KEY,
	AD_ID NUMBER,
	CONSTRAINT FK_BIGCATEGORY_AD FOREIGN KEY(AD_ID)
	REFERENCES TBL_AD(ID)
);

CREATE SEQUENCE SEQ_MEDIUM_CATEGORY;
CREATE TABLE TBL_MEDIUM_CATEGORY(
	ID NUMBER CONSTRAINT PK_MEDIUM_CATEGORY PRIMARY KEY,
	BIGCATEGORY_ID NUMBER,
	CONSTRAINT FK_MEDIUM_CATEGORY_BIGCATEGORY FOREIGN KEY(BIGCATEGORY_ID)
	REFERENCES TBL_BIGCATEGORY(ID)
);


CREATE SEQUENCE SEQ_SMALL_CATEGORY;
CREATE TABLE TBL_SMALL_CATEGORY(
	ID NUMBER CONSTRAINT PK_SMALL_CATEGORY PRIMARY KEY,
	MEDIUM_CATEGORY_ID NUMBER,
	CONSTRAINT FK_SMALL_CATEGORY_MEDIUM_CATEGORY FOREIGN KEY(MEDIUM_CATEGORY_ID)
	REFERENCES TBL_MEDIUM_CATEGORY(ID)
);


CREATE SEQUENCE SEQ_FORM;
CREATE TABLE TBL_FORM(
	ID NUMBER CONSTRAINT PK_FORM PRIMARY KEY,
	COMPANY_ID NUMBER,
	AD_ID NUMBER,
	CONSTRAINT FK_FORM_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_FORM_AD FOREIGN KEY(AD_ID)
	REFERENCES TBL_AD(ID)
);


--=================================================================================================================================

/*
	요구사항
	음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
	음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
	당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/
























